'use strict';

module.exports = {
  ApplicationCache: require('./application-cache'),
  CacheStorage: require('./cache-storage'),
  Canvas: require('./canvas'),
  Console: require('./console'),
  CSS: require('./css'),
  Database: require('./database'),
  Debugger: require('./debugger'),
  DOM: require('./dom'),
  DOMDebugger: require('./domdebugger'),
  DOMStorage: require('./domstorage'),
  Emulation: require('./emulation'),
  FileSystem: require('./file-system'),
  HeapProfiler: require('./heap-profiler'),
  IndexedDB: require('./indexed-db'),
  Input: require('./input'),
  Inspector: require('./inspector'),
  LayerTree: require('./layer-tree'),
  Memory: require('./memory'),
  Network: require('./network'),
  Page: require('./page'),
  Profiler: require('./profiler'),
  Rendering: require('./rendering'),
  Runtime: require('./runtime'),
  ServiceWorker: require('./service-worker'),
  Timeline: require('./timeline'),
  Tracing: require('./tracing'),
  Worker: require('./worker')
};
